---
title: 'Final Study Data Analysis'
author: "April Kim, Jennifer Podracky, Saurav Datta"
output:
  pdf_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(data.table)
library(lmtest)
library(pwr)
library(lsr)
library(cobalt)
```


*Read in data and reformat*
```{r}
d2 <- read.csv("241 Participant List - Final Study Results - 20181215.csv", 
                    stringsAsFactors = F, na.strings=c("","NA"))

d2$Q7 <- as.numeric(gsub("\\,", "", d2$Q7))
d2$Q11 <- as.numeric(gsub("\\,", "", d2$Q11))
d2$Q15 <- as.numeric(gsub("\\,", "", d2$Q15))

# Not applicable = 0
# Through digital means = 1
# In person = 2

d2[d2$Q6 %like% "Not applicable", ]$Q6 <- 0
d2[d2$Q10 %like% "Not applicable", ]$Q10 <- 0
d2[d2$Q14 %like% "Not applicable", ]$Q14 <- 0

d2[d2$Q6 %like% "In person", ]$Q6 <- 2
d2[d2$Q10 %like% "In person", ]$Q10 <- 2
d2[d2$Q14 %like% "In person", ]$Q14 <- 2

d2[d2$Q6 %like% "Through digital means", ]$Q6 <- 1
d2[d2$Q10 %like% "Through digital means", ]$Q10 <- 1
d2[d2$Q14 %like% "Through digital means", ]$Q14 <- 1

# names(d2) <- c("name", "email", "know_us", "day1_treatment", "step_day1", "day2_treatment", "step_day2", "day3_treatment", "step_day3", "treatment_seq")

names(d2) <- c("user_id", "treatment_seq", "location_lat", "location_long", "name", "email", "gender", "gender_code", "age_range", "age_range_code", "location", "lives_with_others", "lives_with_others_code", "submitted_response", "noncompliance_ind", "know_us",
               "day1_num_persons", "day1_treatment", "day1_steps", "day1_upload_id", "day1_upload_filename", "day1_upload_size", "day_1_upload_filetype", 
               "day2_num_persons", "day2_treatment", "day2_steps", "day2_upload_id", "day2_upload_filename", "day2_upload_size", "day_2_upload_filetype",
               "day3_num_persons", "day3_treatment", "day3_steps", "day3_upload_id", "day3_upload_filename", "day3_upload_size", "day3_upload_filetype")


```


```{r}
# response stats
sum(d2$submitted_response)/nrow(d2) # 68% reponse rate

table(d2$gender, d2$submitted_response)
table(d2$age_range, d2$submitted_response)

barplot(table(d2$gender[d2$submitted_response == 1]), main = 'Responses by Gender', xlab = 'Gender', ylab = 'Count')
barplot(table(d2$age_range[d2$submitted_response == 1]), main = 'Responses by Age', xlab = 'Age Range', ylab = 'Count')
barplot(table(d2$lives_with_others[d2$submitted_response == 1]), main = 'Responses by Living Status', xlab = 'Living Status', ylab = 'Count')
```

```{r}
# encode demographics
# gender
d2$gender[d2$gender == "Male"] <- 0
d2$gender[d2$gender == "Female"] <- 1
d2$gender[d2$gender == "Gender non-conforming"] <- 2
d2$gender[is.na(d2$gender)] <- 2
d2$gender <- as.factor(d2$gender)

# age
d2$age_range[d2$age_range == "18 - 24"] <- 0
d2$age_range[d2$age_range == "25 - 34"] <- 1
d2$age_range[d2$age_range == "35 - 44"] <- 2
d2$age_range[d2$age_range == "45 - 54"] <- 3
d2$age_range[d2$age_range == "55 - 64"] <- 4
d2$age_range[d2$age_range == "65+"] <- 5
d2$age_range[is.na(d2$age_range)] <- 6
d2$age_range <- as.factor(d2$age_range)

# lives with others
d2$lives_with_others[d2$lives_with_others == "Alone"] <- 0
d2$lives_with_others[d2$lives_with_others == "With others"] <- 1
d2$lives_with_others[is.na(d2$lives_with_others)] <- 2
d2$lives_with_others <- as.factor(d2$lives_with_others)

# knows us
d2$know_us[d2$know_us == "No"] <- 0
d2$know_us[d2$know_us == "Yes"] <- 1
d2$know_us[is.na(d2$know_us)] <- 2
d2$know_us <- as.factor(d2$know_us)

# covariate balance
bal.tab(treatment_seq ~ gender + age_range + lives_with_others + know_us + location_lat + location_long, 
        data = d2)
cov_check <- lm(treatment_seq ~ gender + age_range + lives_with_others + know_us + location_lat + location_long, 
        data = d2)
summary(cov_check)
```


RESULTS:

[April's sequencing effect analysis, which I borked]
We do not see that the previous days' treatment assignments to predict the last day's step count is highly predicitive and significant, which is super for us!

*Condense treatment sequence to 1 treatment per row*
```{r}
# get data frame in workable format, with just responses
df <- d2[d2$submitted_response == 1,]
d <- rbindlist(list(df[1:nrow(df),c("user_id", "gender", "age_range", "lives_with_others", "know_us",
                                    "day1_treatment","day1_steps")],
                    df[1:nrow(df),c("user_id", "gender", "age_range", "lives_with_others", "know_us",
                                    "day2_treatment","day2_steps")],
                    df[1:nrow(df),c("user_id", "gender", "age_range", "lives_with_others", "know_us",
                                    "day3_treatment","day3_steps")]))
names(d) <- c("user_id", "gender", "age_range", "lives_with_others", "know_us", "treatment","steps")
d$outcome <- ifelse(d$steps > 5000, 1, 0)

ITT_lm <- lm(outcome ~ treatment, data = d)
summary(ITT_lm)

ITT_lm_cov <- lm(outcome ~ treatment + age_range + gender + lives_with_others + know_us, data = d)
summary(ITT_lm_cov)

ITT_lm_steps <- lm(steps ~ treatment, data = d, na.action = na.omit)
summary(ITT_lm_steps)

ITT_lm_steps_cov <- lm(steps ~ treatment + age_range + gender + lives_with_others + know_us, data = d)
summary(ITT_lm_steps_cov)

table(d$treatment, d$outcome)

# combine digital and in person as one treatment as
# "Both in person and through digital means"
d1 <- d
d1[d1$treatment == 1 | d1$treatment == 2, ]$treatment <- 3
```

T-test and power calculations
```{r}
###  Control vs digital 
t.test(d[treatment == 0]$outcome, d[treatment == 1]$outcome, paired = F)
cohensD(d[treatment == 0]$outcome, d[treatment == 1]$outcome, method = "unequal")

### Control vs in person 
t.test(d[treatment == 0]$outcome, d[treatment == 2]$outcome, paired = F)
cohensD(d[treatment == 0]$outcome, d[treatment == 2]$outcome, method = "unequal")

### Control vs in person + digital
t.test(d1[treatment == 0]$outcome, d1[treatment == 3]$outcome, paired = F)
cohensD(d1[treatment == 0]$outcome, d1[treatment == 3]$outcome, method = "unequal")

### In person vs digital 
t.test(d[treatment == 2]$outcome, d[treatment == 1]$outcome, paired = F)
```
no significant difference in both comparisons

